## This workflow will do a clean install of node dependencies, and then run the TypeScript compiler
name: TypeScript Check

on:
  pull_request:
    branches: [main]

jobs:
  typescript-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript
        run: npx tsc --noEmit
